<?php

return [
    [
        'title_key'       => 'service_beach_recovery',
        'description_key' => 'service_beach_recovery_desc',
        'description_footer_key' => 'service_beach_recovery_footer',
        'image'           => '/images/services/coastal/beach-recovery/main-service.jpg',
        'hero_image'      => '/images/services/coastal/beach-recovery/hero-image.jpg',
        'gallery_images'  => [
            '/images/services/coastal/beach-recovery/gallery/gallery-1.jpg',
            '/images/services/coastal/beach-recovery/gallery/gallery-2.jpg',
            '/images/services/coastal/beach-recovery/gallery/gallery-3.jpg',
            '/images/services/coastal/beach-recovery/gallery/gallery-4.jpg',
            '/images/services/coastal/beach-recovery/gallery/gallery-5.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_coastal_dunes',
        'description_key' => 'service_coastal_dunes_desc',
        'description_footer_key' => 'service_coastal_dunes_footer',
        'image'           => '/images/services/coastal/coastal-dunes/main-service.jpg',
        'hero_image'      => '/images/services/coastal/coastal-dunes/hero-image.jpg',
        'gallery_images'  => [
            '/images/services/coastal/coastal-dunes/gallery/gallery-1.jpg',
            '/images/services/coastal/coastal-dunes/gallery/gallery-2.jpg',
            '/images/services/coastal/coastal-dunes/gallery/gallery-3.jpg',
            '/images/services/coastal/coastal-dunes/gallery/gallery-4.jpg',
            '/images/services/coastal/coastal-dunes/gallery/gallery-5.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_geotubes',
        'description_key' => 'service_geotubes_desc',
        'description_footer_key' => 'service_geotubes_footer',
        'image'           => '/images/services/coastal/geotubes/main-service.jpg',
        'hero_image'      => '/images/services/coastal/geotubes/hero-image.jpg',
        'gallery_images'  => [
            '/images/services/coastal/geotubes/gallery/gallery-1.jpg',
            '/images/services/coastal/geotubes/gallery/gallery-2.jpg',
            '/images/services/coastal/geotubes/gallery/gallery-3.jpg',
            '/images/services/coastal/geotubes/gallery/gallery-4.jpg',
            '/images/services/coastal/geotubes/gallery/gallery-5.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_breakwaters',
        'description_key' => 'service_breakwaters_desc',
        'description_footer_key' => 'service_breakwaters_footer',
        'image'           => '/images/services/coastal/breakwaters/main-service.jpg',
        'hero_image'      => '/images/services/coastal/breakwaters/hero-image.jpg',
        'gallery_images'  => [
            '/images/services/coastal/breakwaters/gallery/gallery-1.jpg',
            '/images/services/coastal/breakwaters/gallery/gallery-2.jpg',
            '/images/services/coastal/breakwaters/gallery/gallery-3.jpg',
            '/images/services/coastal/breakwaters/gallery/gallery-4.jpg',
            '/images/services/coastal/breakwaters/gallery/gallery-5.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_retaining_walls',
        'description_key' => 'service_retaining_walls_desc',
        'description_footer_key' => 'service_retaining_walls_footer',
        'image'           => '/images/services/coastal/retaining-walls/main-service.jpg',
        'hero_image'      => '/images/services/coastal/retaining-walls/hero-image.jpg',
        'gallery_images'  => [
            '/images/services/coastal/retaining-walls/gallery/gallery-1.jpg',
            '/images/services/coastal/retaining-walls/gallery/gallery-2.jpg',
            '/images/services/coastal/retaining-walls/gallery/gallery-3.jpg',
            '/images/services/coastal/retaining-walls/gallery/gallery-4.jpg',
            '/images/services/coastal/retaining-walls/gallery/gallery-5.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_artificial_reefs',
        'description_key' => 'service_artificial_reefs_desc',
        'description_footer_key' => 'service_artificial_reefs_footer',
        'image'           => '/images/services/coastal/artificial-reefs/main-service.jpg',
        'hero_image'      => '/images/services/coastal/artificial-reefs/hero-image.png',
        'gallery_images'  => [
            '/images/services/coastal/artificial-reefs/gallery/gallery-1.jpg',
            '/images/services/coastal/artificial-reefs/gallery/gallery-2.jpg',
            '/images/services/coastal/artificial-reefs/gallery/gallery-3.jpg',
            '/images/services/coastal/artificial-reefs/gallery/gallery-4.jpg',
            '/images/services/coastal/artificial-reefs/gallery/gallery-5.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_docks',
        'description_key' => 'service_docks_desc',
        'description_footer_key' => 'service_docks_footer',
        'image'           => '/images/services/coastal/docks/main-service.jpg',
        'hero_image'      => '/images/services/coastal/docks/hero-image.jpeg',
        'gallery_images'  => [
            '/images/services/coastal/docks/gallery/gallery-1.jpg',
            '/images/services/coastal/docks/gallery/gallery-2.jpg',
            '/images/services/coastal/docks/gallery/gallery-3.jpg',
            '/images/services/coastal/docks/gallery/gallery-4.jpg',
            '/images/services/coastal/docks/gallery/gallery-5.jpg',
            '/images/services/coastal/docks/gallery/gallery-6.jpg',
            '/images/services/coastal/docks/gallery/gallery-7.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_beaconing',
        'description_key' => 'service_beaconing_desc',
        'description_footer_key' => 'service_beaconing_footer',
        'image'           => '/images/services/coastal/beaconing/main-service.jpg',
        'hero_image'      => '/images/services/coastal/beaconing/hero-image.jpg',
        'gallery_images'  => [
            '/images/services/coastal/beaconing/gallery/gallery-1.jpg',
            '/images/services/coastal/beaconing/gallery/gallery-2.jpg',
            '/images/services/coastal/beaconing/gallery/gallery-3.jpg',
            '/images/services/coastal/beaconing/gallery/gallery-4.jpg',
            '/images/services/coastal/beaconing/gallery/gallery-5.jpg',
            '/images/services/coastal/beaconing/gallery/gallery-6.jpg',
            '/images/services/coastal/beaconing/gallery/gallery-7.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_pile_inspection',
        'description_key' => 'service_pile_inspection_desc',
        'description_footer_key' => 'service_pile_inspection_footer',
        'image'           => '/images/services/coastal/pile-inspection/main-service.jpg',
        'hero_image'      => '/images/services/coastal/pile-inspection/hero-image.jpg',
        'gallery_images'  => [
            '/images/services/coastal/pile-inspection/gallery/gallery-1.jpg',
            '/images/services/coastal/pile-inspection/gallery/gallery-2.jpg',
            '/images/services/coastal/pile-inspection/gallery/gallery-3.jpg',
            '/images/services/coastal/pile-inspection/gallery/gallery-4.jpg',
            '/images/services/coastal/pile-inspection/gallery/gallery-5.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_dredging',
        'description_key' => 'service_dredging_desc',
        'description_footer_key' => null,
        'image'           => '/images/services/coastal/dredging/main-service.jpg',
        'hero_image'      => '/images/services/coastal/dredging/hero-image.jpg',
        'gallery_images'  => [
            '/images/services/coastal/dredging/gallery/gallery-1.jpg',
            '/images/services/coastal/dredging/gallery/gallery-2.jpg',
            '/images/services/coastal/dredging/gallery/gallery-3.jpg',
            '/images/services/coastal/dredging/gallery/gallery-4.jpg',
            '/images/services/coastal/dredging/gallery/gallery-5.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_submarine_pipelines',
        'description_key' => 'service_submarine_pipelines_desc',
        'description_footer_key' => null,
        'image'           => '/images/services/coastal/submarine-pipelines/main-service.jpg',
        'hero_image'      => '/images/services/coastal/submarine-pipelines/hero-image.jpg',
        'gallery_images'  => [
            '/images/services/coastal/submarine-pipelines/gallery/gallery-1.jpg',
            '/images/services/coastal/submarine-pipelines/gallery/gallery-2.jpg',
            '/images/services/coastal/submarine-pipelines/gallery/gallery-3.jpg',
            '/images/services/coastal/submarine-pipelines/gallery/gallery-4.jpg',
            '/images/services/coastal/submarine-pipelines/gallery/gallery-5.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_submarine_cables',
        'description_key' => 'service_submarine_cables_desc',
        'description_footer_key' => 'service_submarine_cables_footer',
        'image'           => '/images/services/coastal/submarine-cable/main-service.jpg',
        'hero_image'      => '/images/services/coastal/submarine-cable/hero-image.jpg',
        'gallery_images'  => [
            '/images/services/coastal/submarine-cable/gallery/gallery-1.jpg',
            '/images/services/coastal/submarine-cable/gallery/gallery-2.jpg',
            '/images/services/coastal/submarine-cable/main-service.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_salvage',
        'description_key' => 'service_salvage_desc',
        'description_footer_key' => null,
        'image'           => '/images/services/coastal/salvage/main-service.jpg',
        'hero_image'      => '/images/services/coastal/salvage/hero-image.jpg',
        'gallery_images'  => [
            '/images/services/coastal/salvage/gallery/gallery-1.jpg',
            '/images/services/coastal/salvage/gallery/gallery-2.jpg',
            '/images/services/coastal/salvage/gallery/gallery-3.jpg',
            '/images/services/coastal/salvage/gallery/gallery-4.jpg',
            '/images/services/coastal/salvage/gallery/gallery-5.jpg',
            '/images/services/coastal/salvage/gallery/gallery-6.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_underwater_welding',
        'description_key' => 'service_underwater_welding_desc',
        'description_footer_key' => null,
        'image'           => '/images/services/coastal/underwater-welding/main-service.jpg',
        'hero_image'      => '/images/services/coastal/underwater-welding/hero-image.jpg',
        'gallery_images'  => [
            '/images/services/coastal/underwater-welding/gallery/gallery-1.jpg',
            '/images/services/coastal/underwater-welding/gallery/gallery-2.jpg',
            '/images/services/coastal/underwater-welding/gallery/gallery-3.jpg',
            '/images/services/coastal/underwater-welding/gallery/gallery-4.jpg',
            '/images/services/coastal/underwater-welding/gallery/gallery-5.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_underwater_inspection',
        'description_key' => 'service_underwater_inspection_desc',
        'description_footer_key' => 'service_underwater_inspection_footer',
        'image'           => '/images/services/coastal/underwater-inspection/main-service.jpeg',
        'hero_image'      => '/images/services/coastal/underwater-inspection/hero-image.png',
        'gallery_images'  => [
            '/images/services/coastal/underwater-inspection/gallery/gallery-1.jpg',
            '/images/services/coastal/underwater-inspection/gallery/gallery-2.jpg',
            '/images/services/coastal/underwater-inspection/gallery/gallery-3.jpg',
            '/images/services/coastal/underwater-inspection/gallery/gallery-4.jpg',
            '/images/services/coastal/underwater-inspection/gallery/gallery-5.jpg',
            '/images/services/coastal/underwater-inspection/gallery/gallery-6.jpg',
            '/images/services/coastal/underwater-inspection/gallery/gallery-7.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_technical_assessment',
        'description_key' => 'service_technical_assessment_desc',
        'description_footer_key' => null,
        'image'           => '/images/services/coastal/technical-assessment/main-service.jpg',
        'hero_image'      => '/images/services/coastal/technical-assessment/hero-image.jpg',
        'gallery_images'  => [
            '/images/services/coastal/technical-assessment/gallery/gallery-1.jpg',
            '/images/services/coastal/technical-assessment/hero-image.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_sargassum_management',
        'description_key' => 'service_sargassum_management_desc',
        'description_footer_key' => 'service_sargassum_management_footer',
        'image'           => '/images/services/coastal/sargassum-management/main-service.jpg',
        'hero_image'      => '/images/services/coastal/sargassum-management/hero-image.jpg',
        'gallery_images'  => [
            '/images/services/coastal/sargassum-management/gallery/gallery-1.jpg',
            '/images/services/coastal/sargassum-management/gallery/gallery-2.jpg',
            '/images/services/coastal/sargassum-management/gallery/gallery-3.jpg',
            '/images/services/coastal/sargassum-management/gallery/gallery-4.jpg',
            '/images/services/coastal/sargassum-management/gallery/gallery-5.jpg',
            '/images/services/coastal/sargassum-management/gallery/gallery-6.jpg',
        ],
        'show_features'   => true,
    ],
];
