<?php

return [
    [
        'title_key'       => 'service_beach_recovery',
        'description_key' => 'service_beach_recovery_desc',
        'description_footer_key' => 'service_beach_recovery_footer',
        'image'           => 'https://images.pexels.com/photos/1098365/pexels-photo-1098365.jpeg?auto=compress&cs=tinysrgb&w=1280',
        'gallery_images'  => [
            'https://images.pexels.com/photos/1098365/pexels-photo-1098365.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/3934854/pexels-photo-3934854.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/4009175/pexels-photo-4009175.jpeg?auto=compress&cs=tinysrgb&w=1280',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_coastal_dunes',
        'description_key' => 'service_coastal_dunes_desc',
        'description_footer_key' => 'service_coastal_dunes_footer',
        'image'           => 'https://images.pexels.com/photos/635279/pexels-photo-635279.jpeg?auto=compress&cs=tinysrgb&w=1280',
        'gallery_images'  => [
            'https://images.pexels.com/photos/635279/pexels-photo-635279.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/1590247/pexels-photo-1590247.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/1705254/pexels-photo-1705254.jpeg?auto=compress&cs=tinysrgb&w=1280',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_geotubes',
        'description_key' => 'service_geotubes_desc',
        'description_footer_key' => 'service_geotubes_footer',
        'image'           => 'https://images.pexels.com/photos/1001682/pexels-photo-1001682.jpeg?auto=compress&cs=tinysrgb&w=1280',
        'gallery_images'  => [
            'https://images.pexels.com/photos/1001682/pexels-photo-1001682.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/1295138/pexels-photo-1295138.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/1268865/pexels-photo-1268865.jpeg?auto=compress&cs=tinysrgb&w=1280',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_breakwaters',
        'description_key' => 'service_breakwaters_desc',
        'description_footer_key' => 'service_breakwaters_footer',
        'image'           => 'https://images.pexels.com/photos/1209978/pexels-photo-1209978.jpeg?auto=compress&cs=tinysrgb&w=1280',
        'gallery_images'  => [
            'https://images.pexels.com/photos/1209978/pexels-photo-1209978.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/2397651/pexels-photo-2397651.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/127673/pexels-photo-127673.jpeg?auto=compress&cs=tinysrgb&w=1280',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_retaining_walls',
        'description_key' => 'service_retaining_walls_desc',
        'description_footer_key' => 'service_retaining_walls_footer',
        'image'           => 'https://images.pexels.com/photos/2219024/pexels-photo-2219024.jpeg?auto=compress&cs=tinysrgb&w=1280',
        'gallery_images'  => [
            'https://images.pexels.com/photos/2219024/pexels-photo-2219024.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/2775196/pexels-photo-2775196.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/2480828/pexels-photo-2480828.jpeg?auto=compress&cs=tinysrgb&w=1280',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_artificial_reefs',
        'description_key' => 'service_artificial_reefs_desc',
        'description_footer_key' => 'service_artificial_reefs_footer',
        'image'           => 'https://images.pexels.com/photos/3894857/pexels-photo-3894857.jpeg?auto=compress&cs=tinysrgb&w=1280',
        'gallery_images'  => [
            'https://images.pexels.com/photos/3894857/pexels-photo-3894857.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/3329292/pexels-photo-3329292.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/3331094/pexels-photo-3331094.jpeg?auto=compress&cs=tinysrgb&w=1280',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_docks',
        'description_key' => 'service_docks_desc',
        'description_footer_key' => 'service_docks_footer',
        'image'           => 'https://images.pexels.com/photos/1098365/pexels-photo-1098365.jpeg?auto=compress&cs=tinysrgb&w=1280',
        'gallery_images'  => [
            'https://images.pexels.com/photos/1098365/pexels-photo-1098365.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/3934854/pexels-photo-3934854.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/4009175/pexels-photo-4009175.jpeg?auto=compress&cs=tinysrgb&w=1280',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_beaconing',
        'description_key' => 'service_beaconing_desc',
        'description_footer_key' => 'service_beaconing_footer',
        'image'           => 'https://images.pexels.com/photos/1320684/pexels-photo-1320684.jpeg?auto=compress&cs=tinysrgb&w=1280',
        'gallery_images'  => [
            'https://images.pexels.com/photos/1320684/pexels-photo-1320684.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/1320684/pexels-photo-1320684.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/1320684/pexels-photo-1320684.jpeg?auto=compress&cs=tinysrgb&w=1280',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_buoy_lines',
        'description_key' => 'service_buoy_lines_desc',
        'description_footer_key' => 'service_buoy_lines_footer',
        'image'           => 'https://images.pexels.com/photos/1295036/pexels-photo-1295036.jpeg?auto=compress&cs=tinysrgb&w=1280',
        'gallery_images'  => [
            'https://images.pexels.com/photos/1295036/pexels-photo-1295036.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/1295036/pexels-photo-1295036.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/1295036/pexels-photo-1295036.jpeg?auto=compress&cs=tinysrgb&w=1280',
        ],
        'show_features'   => false,
    ],
    [
        'title_key'       => 'service_pile_inspection',
        'description_key' => 'service_pile_inspection_desc',
        'description_footer_key' => 'service_pile_inspection_footer',
        'image'           => 'https://images.pexels.com/photos/2132126/pexels-photo-2132126.jpeg?auto=compress&cs=tinysrgb&w=1280',
        'gallery_images'  => [
            'https://images.pexels.com/photos/2132126/pexels-photo-2132126.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/2132126/pexels-photo-2132126.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/2132126/pexels-photo-2132126.jpeg?auto=compress&cs=tinysrgb&w=1280',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_dredging',
        'description_key' => 'service_dredging_desc',
        'description_footer_key' => null,
        'image'           => 'https://images.pexels.com/photos/753619/pexels-photo-753619.jpeg?auto=compress&cs=tinysrgb&w=1280',
        'gallery_images'  => [
            'https://images.pexels.com/photos/753619/pexels-photo-753619.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/753619/pexels-photo-753619.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/753619/pexels-photo-753619.jpeg?auto=compress&cs=tinysrgb&w=1280',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_submarine_pipelines',
        'description_key' => 'service_submarine_pipelines_desc',
        'description_footer_key' => null,
        'image'           => 'https://images.pexels.com/photos/2086621/pexels-photo-2086621.jpeg?auto=compress&cs=tinysrgb&w=1280',
        'gallery_images'  => [
            'https://images.pexels.com/photos/2086621/pexels-photo-2086621.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/2086621/pexels-photo-2086621.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/2086621/pexels-photo-2086621.jpeg?auto=compress&cs=tinysrgb&w=1280',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_submarine_cables',
        'description_key' => 'service_submarine_cables_desc',
        'description_footer_key' => 'service_submarine_cables_footer',
        'image'           => 'https://images.pexels.com/photos/1117210/pexels-photo-1117210.jpeg?auto=compress&cs=tinysrgb&w=1280',
        'gallery_images'  => [
            'https://images.pexels.com/photos/1117210/pexels-photo-1117210.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/1117210/pexels-photo-1117210.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/1117210/pexels-photo-1117210.jpeg?auto=compress&cs=tinysrgb&w=1280',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_salvage',
        'description_key' => 'service_salvage_desc',
        'description_footer_key' => null,
        'image'           => 'https://images.pexels.com/photos/1295036/pexels-photo-1295036.jpeg?auto=compress&cs=tinysrgb&w=1280',
        'gallery_images'  => [
            'https://images.pexels.com/photos/1295036/pexels-photo-1295036.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/1295036/pexels-photo-1295036.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/1295036/pexels-photo-1295036.jpeg?auto=compress&cs=tinysrgb&w=1280',
        ],
        'show_features'   => true,
    ],
];
