<?php

return [
    [
        'title_key'       => 'service_beach_recovery',
        'description_key' => 'service_beach_recovery_desc',
        'description_footer_key' => 'service_beach_recovery_footer',
        'image'           => '/images/services/coastal/beach-recovery/main-service.jpg',
        'gallery_images'  => [
            '/images/services/coastal/beach-recovery/gallery/gallery-1.jpg',
            '/images/services/coastal/beach-recovery/gallery/gallery-2.jpg',
            '/images/services/coastal/beach-recovery/gallery/gallery-3.jpg',
            '/images/services/coastal/beach-recovery/gallery/gallery-4.jpg',
            '/images/services/coastal/beach-recovery/gallery/gallery-5.jpg',
            '/images/services/coastal/beach-recovery/gallery/gallery-6.jpg',
            '/images/services/coastal/beach-recovery/gallery/gallery-7.jpg',
            '/images/services/coastal/beach-recovery/main-service.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_coastal_dunes',
        'description_key' => 'service_coastal_dunes_desc',
        'description_footer_key' => 'service_coastal_dunes_footer',
        'image'           => '/images/services/coastal/coastal-dunes/main-service.jpg',
        'gallery_images'  => [
            '/images/services/coastal/coastal-dunes/gallery/gallery-1.jpg',
            '/images/services/coastal/coastal-dunes/gallery/gallery-2.jpg',
            '/images/services/coastal/coastal-dunes/gallery/gallery-3.jpg',
            '/images/services/coastal/coastal-dunes/main-service.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_geotubes',
        'description_key' => 'service_geotubes_desc',
        'description_footer_key' => 'service_geotubes_footer',
        'image'           => '/images/services/coastal/geotubes/main-service.jpg',
        'gallery_images'  => [
            '/images/services/coastal/geotubes/gallery/gallery-1.jpg',
            '/images/services/coastal/geotubes/gallery/gallery-2.jpg',
            '/images/services/coastal/geotubes/gallery/gallery-3.jpg',
            '/images/services/coastal/geotubes/main-service.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_breakwaters',
        'description_key' => 'service_breakwaters_desc',
        'description_footer_key' => 'service_breakwaters_footer',
        'image'           => '/images/services/coastal/breakwaters/gallery/gallery-1.jpg',
        'gallery_images'  => [
            '/images/services/coastal/breakwaters/gallery/gallery-1.jpg',
            '/images/services/coastal/breakwaters/gallery/gallery-2.jpg',
            '/images/services/coastal/breakwaters/gallery/gallery-3.jpg',
            '/images/services/coastal/breakwaters/gallery/gallery-4.jpg',
            '/images/services/coastal/breakwaters/gallery/gallery-5.jpg',
            '/images/services/coastal/breakwaters/gallery/gallery-6.jpg',
            '/images/services/coastal/breakwaters/gallery/gallery-7.jpg',
            '/images/services/coastal/breakwaters/main-service.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_retaining_walls',
        'description_key' => 'service_retaining_walls_desc',
        'description_footer_key' => 'service_retaining_walls_footer',
        'image'           => '/images/services/coastal/retaining-walls/gallery/gallery-1.jpg',
        'gallery_images'  => [
            '/images/services/coastal/retaining-walls/gallery/gallery-2.jpg',
            '/images/services/coastal/retaining-walls/gallery/gallery-1.jpg',
            '/images/services/coastal/retaining-walls/main-service.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_artificial_reefs',
        'description_key' => 'service_artificial_reefs_desc',
        'description_footer_key' => 'service_artificial_reefs_footer',
        'image'           => '/images/services/coastal/artificial-reefs/main-service.jpg',
        'gallery_images'  => [
            '/images/services/coastal/artificial-reefs/gallery/gallery-1.jpg',
            '/images/services/coastal/artificial-reefs/gallery/gallery-2.jpg',
            '/images/services/coastal/artificial-reefs/gallery/gallery-3.jpg',
            '/images/services/coastal/artificial-reefs/main-service.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_docks',
        'description_key' => 'service_docks_desc',
        'description_footer_key' => 'service_docks_footer',
        'image'           => '/images/services/coastal/docks/main-service.jpg',
        'gallery_images'  => [
            '/images/services/coastal/docks/gallery/gallery-1.jpg',
            '/images/services/coastal/docks/gallery/gallery-2.jpg',
            '/images/services/coastal/docks/gallery/gallery-3.jpg',
            '/images/services/coastal/docks/main-service.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_beaconing',
        'description_key' => 'service_beaconing_desc',
        'description_footer_key' => 'service_beaconing_footer',
        'image'           => '/images/services/coastal/beaconing/main-service.jpg',
        'gallery_images'  => [
            '/images/services/coastal/beaconing/gallery/gallery-1.jpg',
            '/images/services/coastal/beaconing/gallery/gallery-2.jpg',
            '/images/services/coastal/beaconing/main-service.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_buoy_lines',
        'description_key' => 'service_buoy_lines_desc',
        'description_footer_key' => 'service_buoy_lines_footer',
        'image'           => '/images/services/coastal/buoy-lines/main-service.jpg',
        'gallery_images'  => [
            '/images/services/coastal/buoy-lines/gallery/gallery-1.jpg',
            '/images/services/coastal/buoy-lines/gallery/gallery-2.jpg',
            '/images/services/coastal/buoy-lines/gallery/gallery-3.jpg',
            '/images/services/coastal/buoy-lines/main-service.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_pile_inspection',
        'description_key' => 'service_pile_inspection_desc',
        'description_footer_key' => 'service_pile_inspection_footer',
        'image'           => '/images/services/coastal/pile-inspection/main-service.jpg',
        'gallery_images'  => [
            '/images/services/coastal/pile-inspection/gallery/gallery-1.jpg',
            '/images/services/coastal/pile-inspection/gallery/gallery-2.jpg',
            '/images/services/coastal/pile-inspection/main-service.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_dredging',
        'description_key' => 'service_dredging_desc',
        'description_footer_key' => null,
        'image'           => '/images/services/coastal/dredging/main-service.jpg',
        'gallery_images'  => [
            '/images/services/coastal/dredging/gallery/gallery-1.jpg',
            '/images/services/coastal/dredging/gallery/gallery-2.jpg',
            '/images/services/coastal/dredging/gallery/gallery-3.jpg',
            '/images/services/coastal/dredging/main-service.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_submarine_pipelines',
        'description_key' => 'service_submarine_pipelines_desc',
        'description_footer_key' => null,
        'image'           => '/images/services/coastal/submarine-pipelines/main-service.jpg',
        'gallery_images'  => [
            '/images/services/coastal/submarine-pipelines/gallery/gallery-1.png',
            '/images/services/coastal/submarine-pipelines/gallery/gallery-2.jpg',
            '/images/services/coastal/submarine-pipelines/main-service.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_submarine_cables',
        'description_key' => 'service_submarine_cables_desc',
        'description_footer_key' => 'service_submarine_cables_footer',
        'image'           => 'https://images.pexels.com/photos/1117210/pexels-photo-1117210.jpeg?auto=compress&cs=tinysrgb&w=1280',
        'gallery_images'  => [
            'https://images.pexels.com/photos/1117210/pexels-photo-1117210.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/1117210/pexels-photo-1117210.jpeg?auto=compress&cs=tinysrgb&w=1280',
            'https://images.pexels.com/photos/1117210/pexels-photo-1117210.jpeg?auto=compress&cs=tinysrgb&w=1280',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_salvage',
        'description_key' => 'service_salvage_desc',
        'description_footer_key' => null,
        'image'           => '/images/services/coastal/salvage/main-service.jpg',
        'gallery_images'  => [
            '/images/services/coastal/salvage/gallery/gallery-1.jpg',
            '/images/services/coastal/salvage/gallery/gallery-2.jpg',
            '/images/services/coastal/salvage/gallery/gallery-3.jpg',
            '/images/services/coastal/salvage/main-service.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_underwater_welding',
        'description_key' => 'service_underwater_welding_desc',
        'description_footer_key' => null,
        'image'           => '/images/services/coastal/underwater-welding/gallery/gallery-3.jpg',
        'gallery_images'  => [
            '/images/services/coastal/underwater-welding/gallery/gallery-1.jpg',
            '/images/services/coastal/underwater-welding/gallery/gallery-2.jpg',
            '/images/services/coastal/underwater-welding/gallery/gallery-3.jpg',
            '/images/services/coastal/underwater-welding/main-service.jpg'
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_underwater_inspection',
        'description_key' => 'service_underwater_inspection_desc',
        'description_footer_key' => 'service_underwater_inspection_footer',
        'image'           => '/images/services/coastal/underwater-inspection/main-service.jpg',
        'gallery_images'  => [
            '/images/services/coastal/underwater-inspection/gallery/gallery-1.jpg',
            '/images/services/coastal/underwater-inspection/gallery/gallery-2.jpg',
            '/images/services/coastal/underwater-inspection/main-service.jpg',
        ],
        'show_features'   => true,
    ],
    [
        'title_key'       => 'service_technical_assessment',
        'description_key' => 'service_technical_assessment_desc',
        'description_footer_key' => null,
        'image'           => '/images/services/coastal/technical-assessment/main-service.jpg',
        'gallery_images'  => [],
        'show_features'   => true,
    ],
];
