<?php

return [
    [
        'title_key'              => 'service_bathymetry',
        'description_key'        => 'service_bathymetry_desc',
        'description_footer_key' => null,
        'image'                  => 'images/services/oceanographic-studies/bathymetry/main-service.jpg',
        'hero_image'             => 'images/services/oceanographic-studies/bathymetry/hero-image.png',
        'gallery_images'         => [
            'images/services/oceanographic-studies/bathymetry/gallery/gallery-1.png',
            'images/services/oceanographic-studies/bathymetry/gallery/gallery-2.jpg',
            'images/services/oceanographic-studies/bathymetry/gallery/gallery-3.jpg',
            'images/services/oceanographic-studies/bathymetry/gallery/gallery-4.jpg',
            'images/services/oceanographic-studies/bathymetry/gallery/gallery-5.png',
            'images/services/oceanographic-studies/bathymetry/gallery/gallery-6.jpg',
            'images/services/oceanographic-studies/bathymetry/hero-image.png',
        ],
        'show_features'          => true,
    ],
    [
        'title_key'              => 'service_hydrodynamic_modeling',
        'description_key'        => 'service_hydrodynamic_modeling_desc',
        'description_footer_key' => null,
        'image'                  => 'images/services/oceanographic-studies/hydrodynamic-modeling/main-service.png',
        'hero_image'             => 'images/services/oceanographic-studies/hydrodynamic-modeling/hero-image.jpg',
        'gallery_images'         => [
            'images/services/oceanographic-studies/hydrodynamic-modeling/gallery/gallery-1.png',
            'images/services/oceanographic-studies/hydrodynamic-modeling/gallery/gallery-2.jpg',
            'images/services/oceanographic-studies/hydrodynamic-modeling/gallery/gallery-3.jpg',
            'images/services/oceanographic-studies/hydrodynamic-modeling/gallery/gallery-4.png',
            'images/services/oceanographic-studies/hydrodynamic-modeling/gallery/gallery-5.png',
            'images/services/oceanographic-studies/hydrodynamic-modeling/hero-image.jpg',
        ],
        'show_features'          => true,
    ],
    [
        'title_key'              => 'service_coastal_engineering',
        'description_key'        => 'service_coastal_engineering_desc',
        'description_footer_key' => 'service_coastal_engineering_footer_desc',
        'image'                  => 'images/services/oceanographic-studies/coastal-engineering/main-service.jpg',
        'hero_image'             => 'images/services/oceanographic-studies/coastal-engineering/main-service.jpg',
        'gallery_images'         => [
            'images/services/oceanographic-studies/coastal-engineering/gallery/gallery-1.jpg',
            'images/services/oceanographic-studies/coastal-engineering/gallery/gallery-2.jpeg',
            'images/services/oceanographic-studies/coastal-engineering/gallery/gallery-3.jpg',
            'images/services/oceanographic-studies/coastal-engineering/gallery/gallery-4.jpg',
            'images/services/oceanographic-studies/coastal-engineering/gallery/gallery-5.jpeg',
            'images/services/oceanographic-studies/coastal-engineering/gallery/gallery-6.jpg',
            'images/services/oceanographic-studies/coastal-engineering/gallery/gallery-7.jpg',
            'images/services/oceanographic-studies/coastal-engineering/main-service.jpg',
        ],
        'show_features'          => true,
    ],
]; 